refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/temp.log"
    append: false
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
    - requests
# loggers:
#   app::backend::db:
#     level: info
#   app::requests:
#     level: debug
#     appenders:
#       - requests
#     additive: false